[2025-01-27T07:14:29.138+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T07:14:29.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_scraping_etl.testing_scraping manual__2025-01-27T07:14:24.054318+00:00 [queued]>
[2025-01-27T07:14:29.198+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_scraping_etl.testing_scraping manual__2025-01-27T07:14:24.054318+00:00 [queued]>
[2025-01-27T07:14:29.200+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-27T07:14:29.229+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): testing_scraping> on 2025-01-27 07:14:24.054318+00:00
[2025-01-27T07:14:29.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T07:14:29.252+0000] {standard_task_runner.py:72} INFO - Started process 99 to run task
[2025-01-27T07:14:29.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'testing_scraping_etl', 'testing_scraping', 'manual__2025-01-27T07:14:24.054318+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_scraping.py', '--cfg-path', '/tmp/tmpt26s4_k0']
[2025-01-27T07:14:29.264+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask testing_scraping
[2025-01-27T07:14:29.406+0000] {task_command.py:467} INFO - Running <TaskInstance: testing_scraping_etl.testing_scraping manual__2025-01-27T07:14:24.054318+00:00 [running]> on host 6d90e7596ae2
[2025-01-27T07:14:29.586+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ikrar' AIRFLOW_CTX_DAG_ID='testing_scraping_etl' AIRFLOW_CTX_TASK_ID='testing_scraping' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T07:14:24.054318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T07:14:24.054318+00:00'
[2025-01-27T07:14:29.588+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T07:14:29.668+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-01-27T07:14:31.606+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-01-27T07:14:32.726+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-01-27T07:14:33.437+0000] {logger.py:11} INFO - There is no [linux64] chromedriver "132.0.6834.110" for browser google-chrome "132.0.6834" in cache
[2025-01-27T07:14:33.449+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-01-27T07:14:35.636+0000] {logger.py:11} INFO - WebDriver version 132.0.6834.110 selected
[2025-01-27T07:14:35.647+0000] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/linux64/chromedriver-linux64.zip
[2025-01-27T07:14:35.648+0000] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/linux64/chromedriver-linux64.zip
[2025-01-27T07:14:35.765+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-01-27T07:14:37.503+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-01-27T07:14:38.594+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/132.0.6834.110]
[2025-01-27T07:15:12.506+0000] {job.py:229} INFO - Heartbeat recovered after 33.00 seconds
[2025-01-27T07:15:33.270+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping_lm.py", line 20, in scraping_etl
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: tab crashed
  (Session info: chrome=132.0.6834.110)
Stacktrace:
#0 0x562922710dca <unknown>
#1 0x56292220724d <unknown>
#2 0x5629221f0b4e <unknown>
#3 0x5629221efd4e <unknown>
#4 0x5629221ef6dc <unknown>
#5 0x5629221ef3b9 <unknown>
#6 0x5629221ed346 <unknown>
#7 0x5629221ed9ba <unknown>
#8 0x5629221ec311 <unknown>
#9 0x5629221f4814 <unknown>
#10 0x5629221ec05b <unknown>
#11 0x5629221ef02d <unknown>
#12 0x5629221ed346 <unknown>
#13 0x5629221ed9ba <unknown>
#14 0x5629221ec311 <unknown>
#15 0x5629221e2b87 <unknown>
#16 0x5629221ec05b <unknown>
#17 0x5629221eb982 <unknown>
#18 0x5629221eb495 <unknown>
#19 0x56292220965e <unknown>
#20 0x5629221dc67e <unknown>
#21 0x5629221dc161 <unknown>
#22 0x562922287eac <unknown>
#23 0x5629222872f6 <unknown>
#24 0x56292227b833 <unknown>
#25 0x5629222485a0 <unknown>
#26 0x562922249ece <unknown>
#27 0x5629226dabdb <unknown>
#28 0x5629226deb67 <unknown>
#29 0x5629226c63bc <unknown>
#30 0x5629226df727 <unknown>
#31 0x5629226aa74f <unknown>
#32 0x5629226ff938 <unknown>
#33 0x5629226ffb00 <unknown>
#34 0x56292270fc46 <unknown>
#35 0x7f99fa9a61c4 <unknown>

[2025-01-27T07:15:33.676+0000] {job.py:229} INFO - Heartbeat recovered after 21.21 seconds
[2025-01-27T07:15:33.687+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_scraping_etl, task_id=testing_scraping, run_id=manual__2025-01-27T07:14:24.054318+00:00, execution_date=20250127T071424, start_date=20250127T071429, end_date=20250127T071533
[2025-01-27T07:15:33.819+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T07:15:33.823+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 77 for task testing_scraping (Message: tab crashed
  (Session info: chrome=132.0.6834.110)
Stacktrace:
#0 0x562922710dca <unknown>
#1 0x56292220724d <unknown>
#2 0x5629221f0b4e <unknown>
#3 0x5629221efd4e <unknown>
#4 0x5629221ef6dc <unknown>
#5 0x5629221ef3b9 <unknown>
#6 0x5629221ed346 <unknown>
#7 0x5629221ed9ba <unknown>
#8 0x5629221ec311 <unknown>
#9 0x5629221f4814 <unknown>
#10 0x5629221ec05b <unknown>
#11 0x5629221ef02d <unknown>
#12 0x5629221ed346 <unknown>
#13 0x5629221ed9ba <unknown>
#14 0x5629221ec311 <unknown>
#15 0x5629221e2b87 <unknown>
#16 0x5629221ec05b <unknown>
#17 0x5629221eb982 <unknown>
#18 0x5629221eb495 <unknown>
#19 0x56292220965e <unknown>
#20 0x5629221dc67e <unknown>
#21 0x5629221dc161 <unknown>
#22 0x562922287eac <unknown>
#23 0x5629222872f6 <unknown>
#24 0x56292227b833 <unknown>
#25 0x5629222485a0 <unknown>
#26 0x562922249ece <unknown>
#27 0x5629226dabdb <unknown>
#28 0x5629226deb67 <unknown>
#29 0x5629226c63bc <unknown>
#30 0x5629226df727 <unknown>
#31 0x5629226aa74f <unknown>
#32 0x5629226ff938 <unknown>
#33 0x5629226ffb00 <unknown>
#34 0x56292270fc46 <unknown>
#35 0x7f99fa9a61c4 <unknown>
; 99)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping_lm.py", line 20, in scraping_etl
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: tab crashed
  (Session info: chrome=132.0.6834.110)
Stacktrace:
#0 0x562922710dca <unknown>
#1 0x56292220724d <unknown>
#2 0x5629221f0b4e <unknown>
#3 0x5629221efd4e <unknown>
#4 0x5629221ef6dc <unknown>
#5 0x5629221ef3b9 <unknown>
#6 0x5629221ed346 <unknown>
#7 0x5629221ed9ba <unknown>
#8 0x5629221ec311 <unknown>
#9 0x5629221f4814 <unknown>
#10 0x5629221ec05b <unknown>
#11 0x5629221ef02d <unknown>
#12 0x5629221ed346 <unknown>
#13 0x5629221ed9ba <unknown>
#14 0x5629221ec311 <unknown>
#15 0x5629221e2b87 <unknown>
#16 0x5629221ec05b <unknown>
#17 0x5629221eb982 <unknown>
#18 0x5629221eb495 <unknown>
#19 0x56292220965e <unknown>
#20 0x5629221dc67e <unknown>
#21 0x5629221dc161 <unknown>
#22 0x562922287eac <unknown>
#23 0x5629222872f6 <unknown>
#24 0x56292227b833 <unknown>
#25 0x5629222485a0 <unknown>
#26 0x562922249ece <unknown>
#27 0x5629226dabdb <unknown>
#28 0x5629226deb67 <unknown>
#29 0x5629226c63bc <unknown>
#30 0x5629226df727 <unknown>
#31 0x5629226aa74f <unknown>
#32 0x5629226ff938 <unknown>
#33 0x5629226ffb00 <unknown>
#34 0x56292270fc46 <unknown>
#35 0x7f99fa9a61c4 <unknown>

[2025-01-27T07:15:33.917+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-27T07:15:34.093+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T07:15:34.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
